name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    if: ${{ github.head_ref }} == "master"
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Test
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          yarn
          yarn test
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.LIFEOMIC_NPM_TOKEN}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
